[package]
name = "lockstitch"
version = "0.4.1"
edition = "2021"
authors = ["Coda Hale <coda.hale@gmail.com>"]
license = "MIT"
description = "Lockstitch is an incremental, stateful cryptographic primitive for symmetric-key cryptographic operations in complex protocols. "
homepage = "https://github.com/codahale/lockstitch"
documentation = "https://docs.rs/lockstitch/"
keywords = ["crypto", "rocca-s", "hazmat"]
categories = ["cryptography", "no-std"]
readme = "README.md"
include = ["src/**/*", "benches/**/*", "tests/**/*", "LICENSE", "README.md", "design.md", "perf.md"]

[dependencies]
aligned = "0.4.1"
constant_time_eq = "0.2.4"
rand_core = { version = "0.6.4", default-features = false, optional = true }

[features]
default = ["hedge", "std"]
hedge = ["rand_core"]
std = []

[workspace]
members = ["xtask"]

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
hex = "0.4.3"
hex-literal = "0.3.4"
proptest = "1.0.0"
rand = "0.8.5"

[[bench]]
name = "benchmarks"
harness = false

[package.metadata.release]
pre-release-commit-message = "release: version {{version}}"
tag-message = "release: {{crate_name}} version {{version}}"
