[package]
name = "lockstitch"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = { version = "1.3.1", default-features = false, features = ["std"] }
c2-chacha = { version = "0.3.3", features = ["std", "simd"], default-features = false }
constant_time_eq = "0.2.4"
rand_core = { version = "0.6.4", default-features = false, optional = true }

[features]
default = ["hedge"]
hedge = ["rand_core"]

[workspace]
members = ["xtask"]

[dev-dependencies]
criterion = "0.4.0"
proptest = "1.0.0"

[[bench]]
name = "benchmarks"
harness = false
