[package]
name = "lockstitch"
version = "0.11.1"
edition = "2021"
authors = ["Coda Hale <coda.hale@gmail.com>"]
license = "MIT"
description = "Lockstitch is an incremental, stateful cryptographic primitive for symmetric-key cryptographic operations in complex protocols. "
homepage = "https://github.com/codahale/lockstitch"
documentation = "https://docs.rs/lockstitch/"
keywords = ["crypto", "aegis-128l", "sha-256", "hazmat"]
categories = ["cryptography", "no-std"]
readme = "README.md"
include = ["src/**/*", "benches/**/*", "tests/**/*", "LICENSE", "README.md", "design.md", "perf.md"]

[dependencies]
aes = { version = "0.8.2", features = ["hazmat"], optional = true }
rand_core = { version = "0.6.4", default-features = false, optional = true }
sha2 = { version = "0.10.7", default-features = false }
subtle = { version = "2.5.0", default-features = false }

[features]
default = ["hedge", "std"]
asm = ["sha2/asm"]
hedge = ["rand_core"]
portable = ["aes"]
std = []

[workspace]
members = ["xtask"]

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
expect-test = "1.4.1"
hex = "0.4.3"
hex-literal = "0.4.1"
proptest = "1.2.0"
rand = "0.8.5"

[[bench]]
name = "benchmarks"
harness = false

[package.metadata.release]
pre-release-commit-message = "release: version {{version}}"
tag-message = "release: {{crate_name}} version {{version}}"
