[package]
name = "lockstitch"
version = "0.15.0"
edition = "2021"
authors = ["Coda Hale <coda.hale@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Lockstitch is an incremental, stateful cryptographic primitive for symmetric-key cryptographic operations in complex protocols. "
homepage = "https://github.com/codahale/lockstitch"
documentation = "https://docs.rs/lockstitch/"
keywords = ["crypto", "aes-128-ctr", "sha-256", "hazmat"]
categories = ["cryptography", "no-std"]
readme = "README.md"
include = [
    "src/**/*",
    "benches/**/*",
    "tests/**/*",
    "proptest-regressions",
    "LICENSE-*",
    "README.md",
    "design.md",
    "perf.md",
]

[dependencies]
aes = "0.8.3"
cmov = "0.3.1"
ctr = "0.9.2"
rand_core = { version = "0.6.4", default-features = false, optional = true }
sha2 = "0.10.8"

[features]
asm = ["sha2/asm"]
default = ["asm", "hedge", "std"]
docs = []
hedge = ["rand_core"]
std = []

[workspace]
members = ["xtask"]

[dev-dependencies]
divan = "0.1.0"
expect-test = "1.4.1"
hex = "0.4.3"
hex-literal = "0.4.1"
proptest = "1.3.1"
rand = "0.8.5"

[[bench]]
name = "benchmarks"
harness = false

[package.metadata.docs.rs]
all-features = true

[package.metadata.release]
pre-release-commit-message = "release: version {{version}}"
tag-message = "release: {{crate_name}} version {{version}}"
