[package]
name = "lockstitch"
version = "0.16.3"
edition = "2021"
authors = ["Coda Hale <coda.hale@gmail.com>"]
license = "MIT"
description = "Lockstitch is an incremental, stateful cryptographic primitive for symmetric-key cryptographic operations in complex protocols. "
homepage = "https://github.com/codahale/lockstitch"
documentation = "https://docs.rs/lockstitch/"
keywords = ["crypto", "aegis-128l", "sha-256", "hazmat"]
categories = ["cryptography", "no-std"]
readme = "README.md"
include = [
    "src/aegis_128l.rs",
    "src/intrinsics/aarch64.rs",
    "src/intrinsics/portable.rs",
    "src/intrinsics/x86_64.rs",
    "src/intrinsics.rs",
    "src/lib.rs",
    "tests/constructions_test.rs",
    "tests/transcripts_test.rs",
    "LICENSE",
    "README.md",
    "design.md",
    "perf.md",
]

[dependencies]
aes = { version = "0.8.3", features = ["hazmat"], optional = true }
cmov = "0.3.1"
rand_core = { version = "0.6.4", default-features = false, optional = true }
sha2 = { version = "0.10.8", default-features = false }

[features]
asm = ["sha2/asm"]
default = ["asm", "hedge", "std"]
docs = []
hedge = ["rand_core"]
portable = ["aes"]
std = []

[workspace]
members = ["benchmarks", "xtask"]

[dev-dependencies]
aegis = { version = "0.5.0", features = ["pure-rust"] }
bolero = "0.10.0"
expect-test = "1.4.1"
hex = "0.4.3"
hex-literal = "0.4.1"
rand = "0.8.5"

[package.metadata.docs.rs]
all-features = true

[package.metadata.release]
pre-release-commit-message = "release: version {{version}}"
tag-message = "release: {{crate_name}} version {{version}}"
consolidate-commits = false

[profile.fuzz]
inherits = "dev"
opt-level = 3
incremental = false
codegen-units = 1
