[package]
name = "lockstitch"
version = "0.25.2"
edition = "2021"
authors = ["Coda Hale <coda.hale@gmail.com>"]
license = "MIT"
description = "Lockstitch is an incremental, stateful cryptographic primitive for symmetric-key cryptographic operations in complex protocols. "
homepage = "https://github.com/codahale/lockstitch"
documentation = "https://docs.rs/lockstitch/"
keywords = ["crypto", "aegis-128l", "turboshake128", "hazmat"]
categories = ["cryptography", "no-std"]
readme = "README.md"
include = ["src/**/*", "tests/**/*", "LICENSE", "README.md", "design.md", "perf.md"]

[dependencies]
aes = { version = "0.8.4", features = ["hazmat"], optional = true }
cmov = "0.3.1"
sha3 = { version = "0.10.8", default-features = false, features = ["asm"] }
zeroize = { version = "1.8.1", features = ["aarch64"], optional = true }

[features]
default = ["std", "zeroize"]
docs = []
portable = ["aes"]
std = []
zeroize = ["dep:zeroize"]

[workspace]
members = ["benchmarks", "xtask"]

[dev-dependencies]
aegis = { version = "0.6.7", features = ["pure-rust"] }
bolero = "0.11.1"
expect-test = "1.5.0"
hex = "0.4.3"
hex-literal = "0.4.1"
rand = "0.8.5"
wycheproof = "0.6.0"

[package.metadata.docs.rs]
all-features = true

[package.metadata.release]
pre-release-commit-message = "release: version {{version}}"
tag-message = "release: {{crate_name}} version {{version}}"
consolidate-commits = false

[profile.fuzz]
inherits = "dev"
opt-level = 3
incremental = false
codegen-units = 1

[workspace.lints.rust]
trivial_casts = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
unsafe_op_in_unsafe_fn = "deny"
missing_debug_implementations = "warn"

[workspace.lints.clippy]
cognitive_complexity = "warn"
missing_const_for_fn = "warn"
missing_errors_doc = "warn"
semicolon_if_nothing_returned = "warn"

[lints]
workspace = true
