[package]
name = "lockstitch"
version = "0.1.0"
edition = "2021"
authors = ["Coda Hale <coda.hale@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Lockstitch is an incremental, stateful cryptographic primitive for symmetric-key cryptographic operations in complex protocols. "
homepage = "https://github.com/codahale/lockstitch"
documentation = "https://docs.rs/lockstitch/"
keywords = ["crypto", "blake3", "chacha"]
categories = ["cryptography", "no-std"]
readme = "README.md"
include = [
    "src/**/*",
    "benches/**/*",
    "tests/**/*",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "README.md",
    "design.md",
    "perf.md",
]

[dependencies]
blake3 = { version = "1.3.1", default-features = false }
c2-chacha = { version = "0.3.3", default-features = false }
constant_time_eq = "0.2.4"
rand_core = { version = "0.6.4", default-features = false, optional = true }

[features]
default = ["hedge", "std"]
hedge = ["rand_core"]
std = ["blake3/std", "c2-chacha/std"]

[workspace]
members = ["xtask"]

[dev-dependencies]
criterion = "0.4.0"
proptest = "1.0.0"

[[bench]]
name = "benchmarks"
harness = false
