[package]
name = "lockstitch"
version = "0.12.4"
edition = "2021"
authors = ["Coda Hale <coda.hale@gmail.com>"]
license = "MIT"
description = "Lockstitch is an incremental, stateful cryptographic primitive for symmetric-key cryptographic operations in complex protocols. "
homepage = "https://github.com/codahale/lockstitch"
documentation = "https://docs.rs/lockstitch/"
keywords = ["crypto", "aegis-128l", "sha-256", "hazmat"]
categories = ["cryptography", "no-std"]
readme = "README.md"
include = ["src/**/*", "benches/**/*", "tests/**/*", "LICENSE", "README.md", "design.md", "perf.md"]

[dependencies]
aes = { version = "0.8.3", features = ["hazmat"], optional = true }
cmov = { git = "https://github.com/RustCrypto/utils", branch = "master", package = "cmov" }
rand_core = { version = "0.6.4", default-features = false, optional = true }
sha2 = { version = "0.10.8", default-features = false }

[features]
default = ["asm", "hedge", "std"]
asm = ["sha2/asm"]
hedge = ["rand_core"]
portable = ["aes"]
std = []

[workspace]
members = ["xtask"]

[dev-dependencies]
divan = "0.1.0"
expect-test = "1.4.1"
hex = "0.4.3"
hex-literal = "0.4.1"
proptest = "1.3.1"
rand = "0.8.5"

[[bench]]
name = "benchmarks"
harness = false

[package.metadata.release]
pre-release-commit-message = "release: version {{version}}"
tag-message = "release: {{crate_name}} version {{version}}"
