[package]
name = "benchmarks"
version = "0.0.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divan = "0.1.1"
lockstitch = { path = ".." }

[[bench]]
name = "benchmarks"
harness = false
