[package]
name = "benchmarks"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
divan = "0.1.4"
lockstitch = { path = ".." }

[[bench]]
name = "benchmarks"
harness = false

[package.metadata.release]
release = false
consolidate-commits = false

[lints]
workspace = true
