name: Fuzz
on:
    workflow_dispatch: 
    # schedule:
    #     - cron: "0 0 * * *" 
jobs:
  x86:
    strategy:
      matrix:
        target:
            - aegis_128l::tests::round_trip
            - aegis_128l::tests::interop
            - aead
            - daead
            - tuple_hash
            - stream_cipher
            - hash
            - mac
            - determinism
            - divergence
            - invertible
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-feature=+aes,+ssse3"
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo +stable install cargo-bolero -f
      - run: cargo +nightly bolero test ${{ matrix.target }} -T 5m