name: Fuzz
on:
    workflow_dispatch: 
    schedule:
        - cron: "0 0 * * 0" 
jobs:
  libFuzzer:
    strategy:
      matrix:
        target:
            - tests::encoded_label_injective 
            - tests::left_encode_injective 
            - aead
            - daead
            - tuple_hash
            - stream_cipher
            - hash
            - mac
            - determinism
            - divergence
            - invertible
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo +stable install cargo-bolero -f
      - run: cargo +nightly bolero test ${{ matrix.target }} -T 5m